### ISSUE TITLE
[Feature Request] Rotary Encoder

### ISSUE THREAD

**Issue by jolo2020** [noroadsleft/qmk_firmware#1]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I don't think, that I've chosen the right issue type, sorry about that.
Attached you'll find a picture of soldering work done on an Iris PCB. Is there a way to use the unused pins of the atmega in a similar way (solder the wire of an encoder to holes in the PCB) or do I have to solder directly on the microcontroller (since the wings board has an integrated chip)? 

![20210306_082734](https://user-images.githubusercontent.com/79898156/110198909-06204f00-7e56-11eb-9847-fcd171645a46.jpg)

(Image by jhelvy)

**Comment by noroadsleft** [comment]
Sorry, but I'm greatly confused by your post.

> Well first your post is super helpful! 

You reference a "super helpful" first post that apparently I made, but have started a new issue on my `qmk_firmware` fork; so there's no included context. I don't know what post to which you are referring – if you can link me to the post you're referring to that would be a big help.

> But is it possible to describe which pins are unused? I am new to the qmk language and want to go straight for a big project (adding a encoder to ymdk wings).

I don't know offhand, but it probably wouldn't be hard to determine.

> Furthermore, do you have any actual keymapping after the definition of variables to share?

Not sure what variables you're referring to here. Do you mean for setting up the rotary encoder?

**Comment by jolo2020** [comment]
Sorry my bad it's this post:

https://github.com/noroadsleft/qmk_firmware/blob/master/keyboards/ymdk/wings/config.h

I am quite new to everything so please excuse my stupid questions :).

I would really appreciate some guidance to programming the encoder, where to solder on the atmega32u4 and furthermore a normal keymap (qwerty), because I failed last time programming the keymap :(.

Thank you already!!
